### ISSUE TITLE
Missing luanxml library in release zip file causes failure to load Noita MapCap v2.0.0

### ISSUE THREAD

**Issue by whalehub** [Dadido3/noita-mapcap#15]
### Description
I tried out the new version of this mod on a clean install of Noita today and encountered the following errors when starting a new game with the dev build:

![error](https://xbb.datahoarder.dev/VUSu3/GuzerupE58/raw.png)

### Steps to reproduce
1. Install the latest GOG version of Noita (file: `setup_noita_20210423-1929_(46552).exe`, ingame: `Apr 23 2021 - 18:36:55`) .
2. Download and extract [noita-mapcap-windows-amd64.zip](https://github.com/Dadido3/noita-mapcap/releases/download/v2.0.0/noita-mapcap-windows-amd64.zip) in the `mods` folder.
3. Launch the game with `noita_dev.exe`.
4. Activate the mod.
5. Adjust the mod settings like this:

![modsettings](https://xbb.datahoarder.dev/VUSu3/nuVOjIsU84.png/raw)

6. Start a new game.

### Additional info
I believe the root cause of this issue is that the `luanxml` library is not included in the release file, probably because it is [imported as a Git submodule](https://github.com/Dadido3/noita-mapcap/tree/master/files/libraries). I was only able to use the new version of this mod after manually downloading the `nxml.lua` file [here](https://github.com/zatherz/luanxml/blob/03d28907ccced296e5b2f8b16303a312ab4eaa3b/nxml.lua) and placing it in `C:\Games\Noita\mods\noita-mapcap\files\libraries\luanxml\`.

**Comment by Dadido3** [comment]
Thanks for telling me, i should have tested it on a fresh installation.

The problem was that the github checkout action doesn't download any submodules by default. And therefore it wasn't packed when i created the new release.

If you find anything else, please let me know. It's always hard to test all use cases.
