### ISSUE TITLE
Mod doesn't work on Nightmare Mode (New Game +)

### ISSUE THREAD

**Issue by NoxNebula** [Dadido3/noita-mapcap#2]
I set `custom_activation="0"` in `Noita/mods/nightmare/mod.xml`, to make the Nightmare mode available in the mod menu. Starting a new (normal) game then actually starts the Nightmare mode.
But the mapcap mod is not working if the Nightmare mod is active.

(When I click **Start capturing full map** or **Start capturing map around view**, the Mod-UI just hides and nothing happens.

![nightmare1](https://user-images.githubusercontent.com/293639/69814681-04002700-11f5-11ea-9dbd-d547ac08fec5.PNG)
![nightmare2](https://user-images.githubusercontent.com/293639/69814682-04002700-11f5-11ea-8059-e16bf769a8f3.PNG)
![nightmare3](https://user-images.githubusercontent.com/293639/69814684-04002700-11f5-11ea-80b9-295c0c9bf5e7.PNG)

I can fly around freely but the mod is not doing its thing.

**Comment by Dadido3** [comment]
Gonna investigate on why that happens

**Comment by Dadido3** [comment]
ok, it should be fixed now. Gonna close this issue, if there is still a problem, reopen it or create a new one.

And thanks for telling me about the incompatibility.

**Comment by NoxNebula** [comment]
Rather thank you for the fast fix
+1
