### ISSUE TITLE
New Noita build breaks the option "Disable mod detection"

### ISSUE THREAD

**Issue by whalehub** [Dadido3/noita-mapcap#20]
A new Noita build was released on March 11th this year. Enabling the option "Disable mod detection" now causes the following error message to appear in-game:

![noita_dev_2023-04-16_14-51-00](https://user-images.githubusercontent.com/44198148/232313017-67a2cd81-04d2-49b9-95d7-572d4b90b21f.png)

**Comment by whalehub** [comment]
@Dadido3 Is this option only meant for the normal (non-dev) build of Noita?

**Comment by Dadido3** [comment]
Yes, this only works (and makes sense) with the normal build. I pushed a change to hide this option in dev build.
