### ISSUE TITLE
Error messages are captured on the output images

### ISSUE THREAD

**Issue by whalehub** [Dadido3/noita-mapcap#21]
Using the dev build of the latest Noita release from March 11th, any error messages that occur during the capture process are displayed on the output image like this:

![256,256](https://user-images.githubusercontent.com/44198148/232319616-ae9554a9-b2b0-4e35-afbc-5e1707e51e16.png)

**Comment by Dadido3** [comment]
This is because some of the addresses have changed in Noita, and the mod doesn't know how to disable the UI and some other stuff.

I'll make my mod compatible with the updated Noita version soon, in the meantime you can press `F5`, `F8` and `F12` in the dev build to do the same thing.

**Comment by Dadido3** [comment]
It should work now, updated release is uploaded.
