### ISSUE TITLE
error: Couldn't modify "mFreezeAI" in "processMemory" realm.

### ISSUE THREAD

**Issue by vcup** [Dadido3/noita-mapcap#22]
![image](https://github.com/Dadido3/noita-mapcap/assets/53596976/31b432a8-8de4-4f72-9d75-9e2d1484ab3c)

Version: Noita - Dev Build Jun 19 2023 - 14:14:52a

**Comment by Dadido3** [comment]
Made the mod compatible with the new builds, if there is still some issue related to this feel free to reopen.
