### ISSUE TITLE
An exception happened in Capture:StartCapturing

### ISSUE THREAD

**Issue by ShadowOTC** [Dadido3/noita-mapcap#29]
Dev build: No
Screenshot of the problem:
![image](https://github.com/Dadido3/noita-mapcap/assets/47579857/3caeefe9-3f59-4282-a5d1-30864254c62d)
When it happens: When i try to start to capture
Mod configuration:
![image](https://github.com/Dadido3/noita-mapcap/assets/47579857/a9c4cb39-2a05-4c2f-8fb4-5c179755b407)
Mods enabled:
![image](https://github.com/Dadido3/noita-mapcap/assets/47579857/3a39deec-80af-4b07-ae3e-53c23612eee5)

**Comment by Dadido3** [comment]
Thanks for reporting this bug. It's now fixed in 203a0ea159cb4524878e3be193509127dc73fd11.

A new release will be up in a few minutes.
