### ISSUE TITLE
Worms are not frozen

### ISSUE THREAD

**Issue by NoxNebula** [Dadido3/noita-mapcap#3]
It seems like Worms are the only enemy not to be frozen and they like to eat to the ground and ruin the map capture.

![image-capture (1)](https://user-images.githubusercontent.com/293639/69908498-222f7800-13eb-11ea-92f9-c19d45d6eeb5.png)
![image-capture (2)](https://user-images.githubusercontent.com/293639/69908499-222f7800-13eb-11ea-920e-d5fb9cda6a99.png)

I'm not sure if mods are able to do something about that but I thought I better address this.

**Comment by Dadido3** [comment]
I set the speed of the worms to 0, see 95c53b96a906bee321d611b6f936ab11c06ab6fc.
Worms added in other mods will be unaffected, and/or overwrite the worm behavior again.
