### ISSUE TITLE
stitch ignores output flag

### ISSUE THREAD

**Issue by NoxNebula** [Dadido3/noita-mapcap#4]
Stitch completely ignores the output flag
```console
stitch -output asdf.png
```
still outputs a `output.png`

Just using
```console
stitch
```
and entering the filename there doesn't work either.

**Comment by Dadido3** [comment]
Oh thanks for pointing it out. I didn't test that parameter, and forgot to actually use it in the stitcher. It's fixed with 13373028ccaab7d265785a66dc3e7f308e45b048
